### ISSUE TITLE
"Value cannot be null" for certain accounts

### ISSUE THREAD

**Issue by ReactiveRaven** [scarpentier/SteamParty#17]
https://steamparty.azurewebsites.net/compare?steamids=76561197973934399%2C76561197970866598%2C76561198046661872

The above link generates a 500 error, which includes the following stack trace:

```
[ArgumentNullException: Value cannot be null.
Parameter name: source]
   System.Linq.Enumerable.Select(IEnumerable`1 source, Func`2 selector) +4357034
   SteamParty.Core.SteamApi.GetOwnedGames(String steamId) +240
   SteamParty.Core.Comparer.Compare(IList`1 players) +115
   SteamParty.Core.Comparer.Compare(IList`1 steamIds) +25
   ASP._Page_compare_cshtml.Execute() +291
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +198
   System.Web.WebPages.WebPage.ExecutePageHierarchy(IEnumerable`1 executors) +69
   System.Web.WebPages.WebPage.ExecutePageHierarchy() +131
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +78
   System.Web.WebPages.WebPageHttpHandler.ProcessRequestInternal(HttpContextBase httpContext) +116
```

Removing the last ID from the list, the comparison works properly:

https://steamparty.azurewebsites.net/compare?steamids=76561197973934399%2C76561197970866598

It may be related to the last ID's privacy settings being changed from Private, to Friends Only, and finally unrestricted.

**Comment by scarpentier** [comment]
Hi @ReactiveRaven! Thank you for you report.

Turns out your friend [rotharkon](http://steamcommunity.com/id/rotharkon/) has no games at all and that causes an error [here](https://github.com/scarpentier/SteamParty/blob/master/Core/SteamApi.cs#L93).

I'll have a fix real soon! :-)
