### ISSUE TITLE
no longer working

### ISSUE THREAD

**Issue by antisocialian** [scarpentier/SteamParty#20]
when i enter a name, and click add, it just shows a spinning symbol but does nothing else.

**Comment by Smir** [comment]
+1 doesn't work.

**Comment by MeaKyori** [comment]
This is related to the Steam privacy changes that have now been made.

https://arstechnica.com/gaming/2018/04/steam-spy-announces-its-shutting-down-blames-valves-new-privacy-settings/

How they will fix it, or if they will, I have no idea. I doubt they can honestly.

**Comment by Smir** [comment]
Such a pathetic company. How do we enable this? how comes we can view friends games still if they are meant to be private?

**Comment by MeaKyori** [comment]
It's a reaction to all the privacy issues springing up. They enabled HTTPS too.

Go to your profile, edit, privacy settings, and it's the one for games. It says the bit about displaying your owned games.

You are still able to view friends' games because the default is Friends Only.

**Comment by Smir** [comment]
Yeah figured it out eventually, just a shame as steamspy will close aswell =-/

**Comment by scarpentier** [comment]
Hi peeps! I just tested with the "demo" profiles and it seems to work :-/
It can hang if the profile is not public enough (profile is public but list of games isn't).
Could you send me the profiles you're trying to compare?

**Comment by Smir** [comment]
It’s just a setting steam has changed for everyone. Changing games to public rather than friends fixes it :)

**Comment by MeaKyori** [comment]
In that case, you may want to put some sort of big obvious notification alerting users to this and how to reenable. A lot probably don't even know about the change.
