### ISSUE TITLE
Compare functionality is returning 500

### ISSUE THREAD

**Issue by DvDty** [scarpentier/SteamParty#21]
Stack trace:
`[NullReferenceException: Object reference not set to an instance of an object.]    SteamParty.Core.Comparer.Compare(IList'1 players) +118    SteamParty.Core.Comparer.Compare(IList'1 steamIds) +25    ASP._Page_compare_cshtml.Execute() +291    System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +198    System.Web.WebPages.WebPage.ExecutePageHierarchy(IEnumerable'1 executors) +69    System.Web.WebPages.WebPage.ExecutePageHierarchy() +131    System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +78    System.Web.WebPages.WebPageHttpHandler.ProcessRequestInternal(HttpContextBase httpContext) +116`

The call doesn't have error handle. The front end indicates the request is still running.

**Comment by Nikkiez** [comment]
Pls fix 💯

**Comment by cdrch** [comment]
I'm receiving the same error now.

Edit: Just to note, the demo works without issue.

**Comment by cdrch** [comment]
Update: looks like we just had our game lists set to private. @DvDty @Nikkiez , might try to double-check to ensure that isn't the issue with you.

**Comment by DvDty** [comment]
> Update: looks like we just had our game lists set to private. @DvDty @Nikkiez , might try to double-check to ensure that isn't the issue with you.

I think the web site is down. Is the project dead?

**Comment by scarpentier** [comment]
@DvDty it still works and is available at https://steamparty.azurewebsites.net/

99% of the issues are caused by someone having a profile or game list that's not public.

It's not dead as I'll keep it running and gladly accept any pull requests 🙂

**Comment by RainOrigami** [comment]
I've been trying with my profile:
![image](https://user-images.githubusercontent.com/51454971/181959824-73afd467-bb4f-46e8-bd26-b7b901a55281.png)
these settings should allow the game list to be available but I am getting the 500 error with my profile name and my steamid. What am I missing?
